---
# tasks file for pti.role


#copy /etc/default/grub
- name: copy grub config
  become: yes
  copy:
    src: files/grub
    dest: /etc/default/grub
    owner: root
    group: root
    mode: 0644


- name: update grub
  become: yes
  command: update-grub

- name: Restart server
  become: yes
  command: reboot
  #~ async: 0
  #~ poll: 0
  ignore_errors: true
