---
  - name: apt-get update
    become: yes
    apt: update_cache=yes

  - name: install apache to latest version
    become: yes
    apt: name=apache2 state=latest

  - name: Enable service apache
    service:
      name: apache2
      enabled: yes
