---
# tasks file for benchmark.role
  - name: add 32 bit arch
    become: yes
    command: >
      dpkg --add-architecture i386
      


  - name: apt-get update
    become: yes
    apt: update_cache=yes

  - name: install ab to latest version
    become: yes
    apt: name=apache2-utils state=latest
    

    
  - name: install autobench
    become: yes
    apt:
      deb: http://www.xenoclast.org/autobench/downloads/debian/autobench_2.1.2_i386.deb

  - name: add 32 bit arch
    become: yes
    command: >
      dpkg --add-architecture i386


  - name: install new autobench config file
    command: >
      autobench --version

#autobench

  - name: autobench webpatched
    become: yes
    command: >
      autobench --single_host --host1 192.168.33.100 --quiet --low_rate 20 --high_rate 200 --rate_step 2 --num_call 1 --num_conn 50 --timeout 5 --file /vagrant/autobench_patched.tsv


  - name: autobench webvulnerable
    become: yes
    command: >
      autobench --single_host --host1 192.168.33.101 --quiet --low_rate 20 --high_rate 200 --rate_step 2 --num_call 1 --num_conn 50 --timeout 5 --file /vagrant/autobench_vulnerable.tsv

#ab

  - name: ab webpatched
    become: yes
    command: >
      ab -n 1000 -g /vagrant/ab_patched.txt http://192.168.33.100/

  - name: ab webvulnerable
    become: yes
    command: >
      ab -n 1000 -g /vagrant/ab_vulnerable.txt http://192.168.33.101/

#cpu usage webpatched

  - name: cpu usage webpatched autobench
    become: yes
    shell: nohup autobench --single_host --host1 192.168.33.100 --quiet --low_rate 40 --high_rate 40 --num_call 1 --num_conn 1000 --timeout 5 &

  - name: cpu usage webpatched vmstat
    become: yes
    shell: vmstat 1 30 --one-header> /vagrant/vmstat_patched.dat
    delegate_to: webpatched

#cpu usage webvulnerable

  - name: cpu usage webvulnerable autobench
    become: yes
    shell: nohup autobench --single_host --host1 192.168.33.101 --quiet --low_rate 40 --high_rate 40 --num_call 1 --num_conn 1000 --timeout 5 &

  - name: cpu usage webvulnerable vmstat
    become: yes
    shell: vmstat 1 30 --one-header> /vagrant/vmstat_vulnerable.dat
    delegate_to: webvulnerable


#redis
  - name: install redis tools
    become: yes
    apt: name=redis-tools state=present


  - name: redis benchmark webvulnerable
    become: yes
    shell: >
      redis-benchmark -h 192.168.33.101 -t PING_INLINE,PING_BULK,SET,GET,INCR,LPUSH,LPOP,SADD,SPOP --csv> /vagrant/redis_vulnerable.csv
      
  - name: redis benchmark webpatched
    become: yes
    shell: >
      redis-benchmark -h 192.168.33.100 -t PING_INLINE,PING_BULK,SET,GET,INCR,LPUSH,LPOP,SADD,SPOP --csv> /vagrant/redis_patched.csv
