# -*- mode: ruby -*-
# vi: set ft=ruby :


serverpatched = 
  { :hostname => 'webpatched', :ip => '192.168.33.100', :box => 'ubuntu/trusty64' }


servervulnerable = 
  { :hostname => 'webvulnerable', :ip => '192.168.33.101', :box => 'ubuntu/trusty64' }

loadgenerator = 
  { :hostname => 'loadgenerator', :ip => '192.168.33.102', :box => 'ubuntu/trusty64' }



Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  #config.vm.box = "ubuntu/artful64"
  
  
	  config.vm.define serverpatched[:hostname] do |configpatched|
		  configpatched.vm.box = serverpatched[:box]
		  configpatched.vm.hostname = serverpatched[:hostname]
		  configpatched.vm.network :private_network, ip: serverpatched[:ip]
  		end



	  config.vm.define servervulnerable[:hostname] do |configvulnerable|
	      configvulnerable.vm.box = servervulnerable[:box]
		  configvulnerable.vm.hostname = servervulnerable[:hostname]
		  configvulnerable.vm.network :private_network, ip: servervulnerable[:ip]
        end

	  config.vm.define loadgenerator[:hostname] do |configloadgenerator|
	      configloadgenerator.vm.box = loadgenerator[:box]
		  configloadgenerator.vm.hostname = loadgenerator[:hostname]
		  configloadgenerator.vm.network :private_network, ip: loadgenerator[:ip]
        end




  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     #vb.gui = true
  
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
   end

  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  #


  config.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = 'auto'
  #    ansible.verbose = "vvvv"
      ansible.playbook = "provisioning/playbook.yml"
      ansible.inventory_path = "provisioning/inventory"
#      ansible.become = true
        end
end
