---
  - hosts: webservers
    become: yes
    gather_facts: yes
    roles:
       - mysql.role
       - drupal.role
       - benchmark.role
       
  - hosts: webvulnerable
    roles:
      - pti.role

