---
  - hosts: webservers
    become: yes
    gather_facts: yes
    roles:
       - mysql.role
       - drupal.role
       - redis.role
       
  - hosts: webvulnerable
    roles:
      - pti.role

  - hosts: loadgenerator
    roles:
      - benchmark.role

